version: '3'

services:
  memcached:
    image: 'bitnami/memcached:latest'
    ports:
      - "11211:11211"
  app:
    build:
      context: .
    ports:
      - "8085:8085"
    depends_on:
      - memcached
